#import <Foundation/Foundation.h>
#import "NEBLRpcRequest.h"
#import "NEBLRpcResponse.h"
#import "NEBLApi.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface NEBLJSONRPCApi: NSObject <NEBLApi>

extern NSString* kNEBLJSONRPCApiErrorDomain;
extern NSInteger kNEBLJSONRPCApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(NEBLApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Send a JSON-RPC call to a localhost neblio-Qt or nebliod node
/// Call any Neblio RPC command from the Neblio API libraries. Useful for signing transactions with a local node and other functions. Will not work from a browser due to CORS restrictions. Requires a node to be running locally at 127.0.0.1
///
/// @param rpcRequest 
/// 
///  code:200 message:"Object containing the JSON response from the Neblio node.",
///  code:401 message:"Authentication information is missing or invalid"
///
/// @return NEBLRpcResponse*
-(NSURLSessionTask*) jsonRpcWithRpcRequest: (NEBLRpcRequest*) rpcRequest
    completionHandler: (void (^)(NEBLRpcResponse* output, NSError* error)) handler;



@end
