#import <Foundation/Foundation.h>
#import "NEBLGetFaucetResponse.h"
#import "NEBLApi.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface NEBLTestnetFaucetApi: NSObject <NEBLApi>

extern NSString* kNEBLTestnetFaucetApiErrorDomain;
extern NSInteger kNEBLTestnetFaucetApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(NEBLApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Withdraws testnet NEBL to the specified address
/// Withdraw testnet NEBL to your Neblio Testnet address. By default amount is 1500000000 or 15 NEBL and has a max of 50 NEBL. Only 2 withdrawals allowed per 24 hour period. 
///
/// @param address Your Neblio Testnet Address
/// @param amount Amount of NEBL to withdrawal in satoshis (optional)
/// 
///  code:200 message:"Object containing the transaction ID of the withdrawal."
///
/// @return NEBLGetFaucetResponse*
-(NSURLSessionTask*) testnetGetFaucetWithAddress: (NSString*) address
    amount: (NSNumber*) amount
    completionHandler: (void (^)(NEBLGetFaucetResponse* output, NSError* error)) handler;



@end
