#import <Foundation/Foundation.h>
#import "OAIRpcRequest.h"
#import "OAIRpcResponse.h"
#import "OAIApi.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIJSONRPCApi: NSObject <OAIApi>

extern NSString* kOAIJSONRPCApiErrorDomain;
extern NSInteger kOAIJSONRPCApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Send a JSON-RPC call to a localhost neblio-Qt or nebliod node
/// Call any Neblio RPC command from the Neblio API libraries. Useful for signing transactions with a local node and other functions. Will not work from a browser due to CORS restrictions. Requires a node to be running locally at 127.0.0.1
///
/// @param rpcRequest 
/// 
///  code:200 message:"Object containing the JSON response from the Neblio node.",
///  code:401 message:"Authentication information is missing or invalid"
///
/// @return OAIRpcResponse*
-(NSURLSessionTask*) jsonRpcWithRpcRequest: (OAIRpcRequest*) rpcRequest
    completionHandler: (void (^)(OAIRpcResponse* output, NSError* error)) handler;



@end
