#import <Foundation/Foundation.h>
#import "OAIGetFaucetResponse.h"
#import "OAIApi.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAITestnetFaucetApi: NSObject <OAIApi>

extern NSString* kOAITestnetFaucetApiErrorDomain;
extern NSInteger kOAITestnetFaucetApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Withdraws testnet NEBL to the specified address
/// Withdraw testnet NEBL to your Neblio Testnet address. By default amount is 1500000000 or 15 NEBL and has a max of 50 NEBL. Only 2 withdrawals allowed per 24 hour period. 
///
/// @param address Your Neblio Testnet Address
/// @param amount Amount of NEBL to withdrawal in satoshis (optional)
/// 
///  code:200 message:"Object containing the transaction ID of the withdrawal."
///
/// @return OAIGetFaucetResponse*
-(NSURLSessionTask*) testnetGetFaucetWithAddress: (NSString*) address
    amount: (NSNumber*) amount
    completionHandler: (void (^)(OAIGetFaucetResponse* output, NSError* error)) handler;



@end
