#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGError
@end

@interface SWGError : SWGObject


@property(nonatomic) NSNumber* code;

@property(nonatomic) NSString* message;

@property(nonatomic) NSString* fields;

@end
