#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGGetAddressUtxosResponseInner
@end

@interface SWGGetAddressUtxosResponseInner : SWGObject

/* Address [optional]
 */
@property(nonatomic) NSString* address;
/* Transaction ID [optional]
 */
@property(nonatomic) NSString* txid;
/* vout [optional]
 */
@property(nonatomic) NSNumber* vout;
/* Timestamp [optional]
 */
@property(nonatomic) NSNumber* ts;
/* scriptPubKey [optional]
 */
@property(nonatomic) NSString* scriptPubKey;
/* NEBL amount [optional]
 */
@property(nonatomic) NSNumber* amount;
/* Number of confirmations [optional]
 */
@property(nonatomic) NSNumber* confirmations;

@end
