#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGGetTransactionInfoResponseVin.h"
#import "SWGGetTransactionInfoResponseVout.h"
@protocol SWGGetTransactionInfoResponseVin;
@class SWGGetTransactionInfoResponseVin;
@protocol SWGGetTransactionInfoResponseVout;
@class SWGGetTransactionInfoResponseVout;



@protocol SWGGetTransactionInfoResponse
@end

@interface SWGGetTransactionInfoResponse : SWGObject

/* Transaction in raw hex [optional]
 */
@property(nonatomic) NSString* hex;
/* TXID of transaction [optional]
 */
@property(nonatomic) NSString* txid;
/* Transaction version [optional]
 */
@property(nonatomic) NSNumber* version;
/* Transaction locktime [optional]
 */
@property(nonatomic) NSNumber* locktime;
/* Array of transaction inputs [optional]
 */
@property(nonatomic) NSArray<SWGGetTransactionInfoResponseVin>* vin;
/* Array of transaction outputs [optional]
 */
@property(nonatomic) NSArray<SWGGetTransactionInfoResponseVout>* vout;
/* Block time of this transaction [optional]
 */
@property(nonatomic) NSNumber* blocktime;
/* Block height of this transaction [optional]
 */
@property(nonatomic) NSNumber* blockheight;
/* Total NEBL sent in this transaction in satoshis [optional]
 */
@property(nonatomic) NSNumber* totalsent;
/* Total NEBL used as fee for this transcation in satoshis [optional]
 */
@property(nonatomic) NSNumber* fee;
/* Hash of the block this transaction is in [optional]
 */
@property(nonatomic) NSString* blockhash;
/* Transaction time [optional]
 */
@property(nonatomic) NSNumber* time;
/* Number of transaction confirmations [optional]
 */
@property(nonatomic) NSNumber* confirmations;

@end
