#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGGetTokenHoldersResponseHolders.h"
@protocol SWGGetTokenHoldersResponseHolders;
@class SWGGetTokenHoldersResponseHolders;



@protocol SWGGetTokenHoldersResponse
@end

@interface SWGGetTokenHoldersResponse : SWGObject

/* TokenId of the token [optional]
 */
@property(nonatomic) NSString* tokenId;

@property(nonatomic) NSArray<SWGGetTokenHoldersResponseHolders>* holders;
/* How many decimal points the token is divisble to [optional]
 */
@property(nonatomic) NSNumber* divibility;
/* Whether new issuances of this token are locked [optional]
 */
@property(nonatomic) NSNumber* lockStatus;
/* Whether the tokesn are aggregatable [optional]
 */
@property(nonatomic) NSString* aggregationPolicy;
/* A UTXO of this token [optional]
 */
@property(nonatomic) NSString* someUtxo;

@end
