#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGGetTokenHoldersResponseHolders
@end

@interface SWGGetTokenHoldersResponseHolders : SWGObject


@property(nonatomic) NSString* address;

@property(nonatomic) NSNumber* amount;

@end
