#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGGetFaucetResponseData
@end

@interface SWGGetFaucetResponseData : SWGObject

/* TXID of a successful withdrawal [optional]
 */
@property(nonatomic) NSString* txId;

@end
