#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGGetTxResponse.h"
@protocol SWGGetTxResponse;
@class SWGGetTxResponse;



@protocol SWGGetTxsResponse
@end

@interface SWGGetTxsResponse : SWGObject

/* Number of pages of transactions [optional]
 */
@property(nonatomic) NSNumber* pagesTotal;
/* Array of transaction objects [optional]
 */
@property(nonatomic) NSArray<SWGGetTxResponse>* txs;

@end
