#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGGetTokenMetadataResponseMetadataOfIssuanceData.h"
@protocol SWGGetTokenMetadataResponseMetadataOfIssuanceData;
@class SWGGetTokenMetadataResponseMetadataOfIssuanceData;



@protocol SWGGetTokenMetadataResponseMetadataOfIssuance
@end

@interface SWGGetTokenMetadataResponseMetadataOfIssuance : SWGObject


@property(nonatomic) SWGGetTokenMetadataResponseMetadataOfIssuanceData* data;

@end
