#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGGetFaucetResponseData.h"
@protocol SWGGetFaucetResponseData;
@class SWGGetFaucetResponseData;



@protocol SWGGetFaucetResponse
@end

@interface SWGGetFaucetResponse : SWGObject

/* Whether the withdrawal was successful [optional]
 */
@property(nonatomic) NSString* status;

@property(nonatomic) SWGGetFaucetResponseData* data;

@end
