#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGGetTransactionInfoResponsePreviousOutput.h"
#import "SWGGetTransactionInfoResponseTokens.h"
@protocol SWGGetTransactionInfoResponsePreviousOutput;
@class SWGGetTransactionInfoResponsePreviousOutput;
@protocol SWGGetTransactionInfoResponseTokens;
@class SWGGetTransactionInfoResponseTokens;



@protocol SWGGetTransactionInfoResponseVout
@end

@interface SWGGetTransactionInfoResponseVout : SWGObject

/* Value of the output in NEBL satoshi [optional]
 */
@property(nonatomic) NSNumber* value;
/* Output index [optional]
 */
@property(nonatomic) NSNumber* n;

@property(nonatomic) SWGGetTransactionInfoResponsePreviousOutput* scriptPubKey;

@property(nonatomic) NSArray<SWGGetTransactionInfoResponseTokens>* tokens;
/* Whether this output has now been used [optional]
 */
@property(nonatomic) NSNumber* used;
/* Blockheight of this transaction [optional]
 */
@property(nonatomic) NSNumber* blockheight;
/* Blockheight this output was used in [optional]
 */
@property(nonatomic) NSNumber* usedBlockheight;
/* TXID this output was used in [optional]
 */
@property(nonatomic) NSString* usedTxid;

@end
