#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGGetTransactionInfoResponsePreviousOutput.h"
#import "SWGGetTransactionInfoResponseScriptSig.h"
#import "SWGGetTransactionInfoResponseTokens.h"
@protocol SWGGetTransactionInfoResponsePreviousOutput;
@class SWGGetTransactionInfoResponsePreviousOutput;
@protocol SWGGetTransactionInfoResponseScriptSig;
@class SWGGetTransactionInfoResponseScriptSig;
@protocol SWGGetTransactionInfoResponseTokens;
@class SWGGetTransactionInfoResponseTokens;



@protocol SWGGetTransactionInfoResponseVin
@end

@interface SWGGetTransactionInfoResponseVin : SWGObject

/* TXID of the input [optional]
 */
@property(nonatomic) NSString* txid;
/* output index [optional]
 */
@property(nonatomic) NSNumber* vout;

@property(nonatomic) SWGGetTransactionInfoResponseScriptSig* scriptSig;

@property(nonatomic) NSNumber* sequence;

@property(nonatomic) SWGGetTransactionInfoResponsePreviousOutput* previousOutput;

@property(nonatomic) NSArray<SWGGetTransactionInfoResponseTokens>* tokens;
/* Value of input in NEBL satoshi [optional]
 */
@property(nonatomic) NSNumber* value;

@end
