#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGGetTransactionInfoResponsePreviousOutput
@end

@interface SWGGetTransactionInfoResponsePreviousOutput : SWGObject


@property(nonatomic) NSString* asm;

@property(nonatomic) NSString* hex;

@property(nonatomic) NSNumber* reqSigs;

@property(nonatomic) NSString* type;

@property(nonatomic) NSArray<NSString*>* addresses;

@end
