#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGGetTxResponseVin.h"
#import "SWGGetTxResponseVout.h"
@protocol SWGGetTxResponseVin;
@class SWGGetTxResponseVin;
@protocol SWGGetTxResponseVout;
@class SWGGetTxResponseVout;



@protocol SWGGetTxResponse
@end

@interface SWGGetTxResponse : SWGObject

/* TXID of transaction [optional]
 */
@property(nonatomic) NSString* txid;
/* Transaction version [optional]
 */
@property(nonatomic) NSNumber* version;
/* Transaction locktime [optional]
 */
@property(nonatomic) NSNumber* locktime;
/* Array of transaction inputs [optional]
 */
@property(nonatomic) NSArray<SWGGetTxResponseVin>* vin;
/* Array of transaction outputs [optional]
 */
@property(nonatomic) NSArray<SWGGetTxResponseVout>* vout;
/* Block time of this transaction [optional]
 */
@property(nonatomic) NSNumber* blocktime;
/* Block height of this transaction [optional]
 */
@property(nonatomic) NSNumber* blockheight;
/* Total NEBL sent in this transaction in satoshis [optional]
 */
@property(nonatomic) NSNumber* totalsent;
/* Total NEBL used as fee for this transcation in satoshis [optional]
 */
@property(nonatomic) NSNumber* fee;
/* Hash of the block this transaction is in [optional]
 */
@property(nonatomic) NSString* blockhash;
/* Transaction time [optional]
 */
@property(nonatomic) NSNumber* time;
/* Number of transaction confirmations [optional]
 */
@property(nonatomic) NSNumber* confirmations;
/* Total NEBL output in this transaction [optional]
 */
@property(nonatomic) NSNumber* valueOut;
/* Total NEBL input in this transaction [optional]
 */
@property(nonatomic) NSNumber* valueIn;
/* Total NEBL used in fees for this transaction [optional]
 */
@property(nonatomic) NSNumber* fees;
/* Transcation size in bytes [optional]
 */
@property(nonatomic) NSNumber* size;

@end
