#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGGetTransactionInfoResponseTokens
@end

@interface SWGGetTransactionInfoResponseTokens : SWGObject

/* ID of the token [optional]
 */
@property(nonatomic) NSString* tokenId;
/* Number of tokens [optional]
 */
@property(nonatomic) NSNumber* amount;
/* TXID the token was issued in [optional]
 */
@property(nonatomic) NSString* issueTxid;
/* Decimal places the token is divisible to [optional]
 */
@property(nonatomic) NSNumber* divisibility;
/* Whether issuance of more tokens is locked [optional]
 */
@property(nonatomic) NSNumber* lockStatus;
/* Whether the tokens are aggregatable [optional]
 */
@property(nonatomic) NSString* aggregationPolicy;

@end
