#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGGetBlockResponse
@end

@interface SWGGetBlockResponse : SWGObject

/* Block hash [optional]
 */
@property(nonatomic) NSString* hash;
/* Number of confirmations block has [optional]
 */
@property(nonatomic) NSNumber* confirmations;
/* Block size in bytes [optional]
 */
@property(nonatomic) NSNumber* size;
/* Block height [optional]
 */
@property(nonatomic) NSNumber* height;
/* Block version [optional]
 */
@property(nonatomic) NSNumber* version;
/* Merkleroot of block [optional]
 */
@property(nonatomic) NSString* merkleroot;
/* Array of tx ids in the block [optional]
 */
@property(nonatomic) NSArray<NSString*>* tx;
/* Block time relative to epoch [optional]
 */
@property(nonatomic) NSNumber* time;
/* Block nonce [optional]
 */
@property(nonatomic) NSNumber* nonce;
/* Block bits [optional]
 */
@property(nonatomic) NSString* bits;
/* Block difficulty [optional]
 */
@property(nonatomic) NSNumber* difficulty;
/* Hash of the previous block on the chain [optional]
 */
@property(nonatomic) NSString* previousblockhash;
/* Hash of the next block on the chain [optional]
 */
@property(nonatomic) NSString* nextblockhash;
/* Number of NEBL awarded in this block [optional]
 */
@property(nonatomic) NSNumber* reward;

@end
