#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGGetTransactionInfoResponseScriptSig.h"
@protocol SWGGetTransactionInfoResponseScriptSig;
@class SWGGetTransactionInfoResponseScriptSig;



@protocol SWGGetTxResponseVin
@end

@interface SWGGetTxResponseVin : SWGObject

/* TXID of the input [optional]
 */
@property(nonatomic) NSString* txid;
/* output index [optional]
 */
@property(nonatomic) NSNumber* vout;

@property(nonatomic) SWGGetTransactionInfoResponseScriptSig* scriptSig;

@property(nonatomic) NSNumber* sequence;
/* Value of input in NEBL [optional]
 */
@property(nonatomic) NSNumber* value;
/* Value of input in NEBL satoshi [optional]
 */
@property(nonatomic) NSNumber* valueSat;
/* input index [optional]
 */
@property(nonatomic) NSNumber* n;

@end
