#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGGetTokenMetadataResponseMetadataOfIssuanceDataUserData.h"
@protocol SWGGetTokenMetadataResponseMetadataOfIssuanceDataUserData;
@class SWGGetTokenMetadataResponseMetadataOfIssuanceDataUserData;



@protocol SWGGetTokenMetadataResponseMetadataOfIssuanceData
@end

@interface SWGGetTokenMetadataResponseMetadataOfIssuanceData : SWGObject

/* Token symbol [optional]
 */
@property(nonatomic) NSString* tokenName;
/* Name of token issuer [optional]
 */
@property(nonatomic) NSString* issuer;
/* Token description [optional]
 */
@property(nonatomic) NSString* _description;

@property(nonatomic) SWGGetTokenMetadataResponseMetadataOfIssuanceDataUserData* userData;

@end
