#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGIssueTokenRequestFlags.h"
#import "SWGIssueTokenRequestMetadata.h"
@protocol SWGIssueTokenRequestFlags;
@class SWGIssueTokenRequestFlags;
@protocol SWGIssueTokenRequestMetadata;
@class SWGIssueTokenRequestMetadata;



@protocol SWGIssueTokenRequest
@end

@interface SWGIssueTokenRequest : SWGObject

/* Address issuing the token 
 */
@property(nonatomic) NSString* issueAddress;
/* Number of tokens to issue 
 */
@property(nonatomic) NSNumber* amount;
/* Number of decimal places the token should be divisble by (0-7) 
 */
@property(nonatomic) NSNumber* divisibility;
/* Fee in satoshi to include in the issuance transaction min 1000000000 (10 NEBL) 
 */
@property(nonatomic) NSNumber* fee;
/* whether the token should be reissuable 
 */
@property(nonatomic) NSNumber* reissuable;

@property(nonatomic) SWGIssueTokenRequestFlags* flags;

@property(nonatomic) SWGIssueTokenRequestMetadata* metadata;

@end
