#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGIssueTokenRequestMetadataRulesFeesItems.h"
@protocol SWGIssueTokenRequestMetadataRulesFeesItems;
@class SWGIssueTokenRequestMetadataRulesFeesItems;



@protocol SWGIssueTokenRequestMetadataRulesFees
@end

@interface SWGIssueTokenRequestMetadataRulesFees : SWGObject

/* Array of objects describing fee rules [optional]
 */
@property(nonatomic) NSArray<SWGIssueTokenRequestMetadataRulesFeesItems>* items;
/* Whether this rule can be modified in future transactions [optional]
 */
@property(nonatomic) NSNumber* locked;

@end
