#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGIssueTokenRequestMetadataUrls
@end

@interface SWGIssueTokenRequestMetadataUrls : SWGObject

/* Name of the URL [optional]
 */
@property(nonatomic) NSString* name;
/* Actual URL [optional]
 */
@property(nonatomic) NSString* url;
/* mimeType of URL content [optional]
 */
@property(nonatomic) NSString* mimeType;
/* Hash of data at the URL, used for verification [optional]
 */
@property(nonatomic) NSString* dataHash;

@end
