#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGIssueTokenRequestMetadataEncryptions
@end

@interface SWGIssueTokenRequestMetadataEncryptions : SWGObject

/* userData key to encrypt [optional]
 */
@property(nonatomic) NSString* key;
/* RSA public key used for encryption [optional]
 */
@property(nonatomic) NSString* pubkey;
/* key format (pem or der) [optional]
 */
@property(nonatomic) NSString* format;
/* pkcs1 or pkcs8 [optional]
 */
@property(nonatomic) NSString* type;

@end
