#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGIssueTokenRequestMetadata.h"
#import "SWGSendTokenRequestTo.h"
@protocol SWGIssueTokenRequestMetadata;
@class SWGIssueTokenRequestMetadata;
@protocol SWGSendTokenRequestTo;
@class SWGSendTokenRequestTo;



@protocol SWGSendTokenRequest
@end

@interface SWGSendTokenRequest : SWGObject

/* Fee in satoshi to include in the issuance transaction min 10000 (0.0001 NEBL) 
 */
@property(nonatomic) NSNumber* fee;
/* Array of addresses to send the token from [optional]
 */
@property(nonatomic) NSArray<NSString*>* from;

@property(nonatomic) NSArray<SWGSendTokenRequestTo>* to;

@property(nonatomic) SWGIssueTokenRequestMetadata* metadata;

@end
