#import <Foundation/Foundation.h>
#import "NEBLObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol NEBLRpcRequest
@end

@interface NEBLRpcRequest : NEBLObject

/* JSON-RPC version 
 */
@property(nonatomic) NSString* jsonrpc;
/* Identifier of RCP caller 
 */
@property(nonatomic) NSString* _id;
/* Name of the Neblio RPC method to call 
 */
@property(nonatomic) NSString* method;
/* Array of string params that should be passed to the RPC method. 
 */
@property(nonatomic) NSArray<NSString*>* params;

@end
