#import <Foundation/Foundation.h>
#import "NEBLObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol NEBLIssueTokenRequestMetadataEncryptions
@end

@interface NEBLIssueTokenRequestMetadataEncryptions : NEBLObject

/* userData key to encrypt [optional]
 */
@property(nonatomic) NSString* key;
/* RSA public key used for encryption [optional]
 */
@property(nonatomic) NSString* pubkey;
/* key format (pem or der) [optional]
 */
@property(nonatomic) NSString* format;
/* pkcs1 or pkcs8 [optional]
 */
@property(nonatomic) NSString* type;

@end
