#import <Foundation/Foundation.h>
#import "NEBLObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "NEBLGetTokenMetadataResponseMetadataOfIssuanceDataUserDataMeta.h"
@protocol NEBLGetTokenMetadataResponseMetadataOfIssuanceDataUserDataMeta;
@class NEBLGetTokenMetadataResponseMetadataOfIssuanceDataUserDataMeta;



@protocol NEBLGetTokenMetadataResponseMetadataOfIssuanceDataUserData
@end

@interface NEBLGetTokenMetadataResponseMetadataOfIssuanceDataUserData : NEBLObject


@property(nonatomic) NSArray<NEBLGetTokenMetadataResponseMetadataOfIssuanceDataUserDataMeta>* meta;

@end
