#import <Foundation/Foundation.h>
#import "NEBLObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "NEBLIssueTokenRequestMetadataRulesExpiration.h"
#import "NEBLIssueTokenRequestMetadataRulesFees.h"
#import "NEBLIssueTokenRequestMetadataRulesHolders.h"
@protocol NEBLIssueTokenRequestMetadataRulesExpiration;
@class NEBLIssueTokenRequestMetadataRulesExpiration;
@protocol NEBLIssueTokenRequestMetadataRulesFees;
@class NEBLIssueTokenRequestMetadataRulesFees;
@protocol NEBLIssueTokenRequestMetadataRulesHolders;
@class NEBLIssueTokenRequestMetadataRulesHolders;



@protocol NEBLIssueTokenRequestMetadataRules
@end

@interface NEBLIssueTokenRequestMetadataRules : NEBLObject


@property(nonatomic) NEBLIssueTokenRequestMetadataRulesFees* fees;
/* Array of objects describing what addresses can hold the token [optional]
 */
@property(nonatomic) NSArray<NEBLIssueTokenRequestMetadataRulesHolders>* holders;

@property(nonatomic) NEBLIssueTokenRequestMetadataRulesExpiration* expiration;

@end
