#import <Foundation/Foundation.h>
#import "NEBLObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol NEBLBroadcastTxResponse
@end

@interface NEBLBroadcastTxResponse : NEBLObject

/* Txid of successfully broadcasted transaction [optional]
 */
@property(nonatomic) NSString* txid;

@end
