#import <Foundation/Foundation.h>
#import "NEBLObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol NEBLIssueTokenResponse
@end

@interface NEBLIssueTokenResponse : NEBLObject

/* TokenId of the to be issued token [optional]
 */
@property(nonatomic) NSString* tokenId;
/* Unsigned, raw transaction hex of the transaction to issue the token [optional]
 */
@property(nonatomic) NSString* txHex;

@end
