#import <Foundation/Foundation.h>
#import "NEBLObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "NEBLGetTokenMetadataResponseMetadataOfUtxoUserData.h"
@protocol NEBLGetTokenMetadataResponseMetadataOfUtxoUserData;
@class NEBLGetTokenMetadataResponseMetadataOfUtxoUserData;



@protocol NEBLGetTokenMetadataResponseMetadataOfUtxo
@end

@interface NEBLGetTokenMetadataResponseMetadataOfUtxo : NEBLObject


@property(nonatomic) NEBLGetTokenMetadataResponseMetadataOfUtxoUserData* userData;

@end
