#import <Foundation/Foundation.h>
#import "NEBLObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "NEBLIssueTokenRequestFlags.h"
#import "NEBLIssueTokenRequestMetadata.h"
#import "NEBLSendTokenRequestTo.h"
@protocol NEBLIssueTokenRequestFlags;
@class NEBLIssueTokenRequestFlags;
@protocol NEBLIssueTokenRequestMetadata;
@class NEBLIssueTokenRequestMetadata;
@protocol NEBLSendTokenRequestTo;
@class NEBLSendTokenRequestTo;



@protocol NEBLSendTokenRequest
@end

@interface NEBLSendTokenRequest : NEBLObject

/* Fee in satoshi to include in the issuance transaction min 10000 (0.0001 NEBL) 
 */
@property(nonatomic) NSNumber* fee;
/* Array of addresses to send the token from [optional]
 */
@property(nonatomic) NSArray<NSString*>* from;
/* Array of UTXOs to send the token from [optional]
 */
@property(nonatomic) NSArray<NSString*>* sendutxo;

@property(nonatomic) NSArray<NEBLSendTokenRequestTo>* to;

@property(nonatomic) NEBLIssueTokenRequestFlags* flags;

@property(nonatomic) NEBLIssueTokenRequestMetadata* metadata;

@end
