#import <Foundation/Foundation.h>
#import "NEBLObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol NEBLGetTransactionInfoResponsePreviousOutput
@end

@interface NEBLGetTransactionInfoResponsePreviousOutput : NEBLObject


@property(nonatomic) NSString* asm;

@property(nonatomic) NSString* hex;

@property(nonatomic) NSNumber* reqSigs;

@property(nonatomic) NSString* type;

@property(nonatomic) NSArray<NSString*>* addresses;

@end
