#import <Foundation/Foundation.h>
#import "NEBLObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol NEBLRpcResponse
@end

@interface NEBLRpcResponse : NEBLObject

/* Object containing the response output. [optional]
 */
@property(nonatomic) NSObject* result;
/* Identifier of RCP caller [optional]
 */
@property(nonatomic) NSString* _id;
/* Object containing any error information. [optional]
 */
@property(nonatomic) NSObject* error;

@end
