#import <Foundation/Foundation.h>
#import "NEBLObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol NEBLIssueTokenRequestMetadataUrls
@end

@interface NEBLIssueTokenRequestMetadataUrls : NEBLObject

/* Name of the URL [optional]
 */
@property(nonatomic) NSString* name;
/* Actual URL [optional]
 */
@property(nonatomic) NSString* url;
/* mimeType of URL content [optional]
 */
@property(nonatomic) NSString* mimeType;
/* Hash of data at the URL, used for verification [optional]
 */
@property(nonatomic) NSString* dataHash;

@end
