#import <Foundation/Foundation.h>
#import "NEBLObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "NEBLGetTokenMetadataResponseMetadataOfIssuenceData.h"
@protocol NEBLGetTokenMetadataResponseMetadataOfIssuenceData;
@class NEBLGetTokenMetadataResponseMetadataOfIssuenceData;



@protocol NEBLGetTokenMetadataResponseMetadataOfIssuence
@end

@interface NEBLGetTokenMetadataResponseMetadataOfIssuence : NEBLObject


@property(nonatomic) NEBLGetTokenMetadataResponseMetadataOfIssuenceData* data;

@end
