#import <Foundation/Foundation.h>
#import "NEBLObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "NEBLIssueTokenRequestFlags.h"
#import "NEBLIssueTokenRequestMetadata.h"
#import "NEBLIssueTokenRequestTransfer.h"
@protocol NEBLIssueTokenRequestFlags;
@class NEBLIssueTokenRequestFlags;
@protocol NEBLIssueTokenRequestMetadata;
@class NEBLIssueTokenRequestMetadata;
@protocol NEBLIssueTokenRequestTransfer;
@class NEBLIssueTokenRequestTransfer;



@protocol NEBLIssueTokenRequest
@end

@interface NEBLIssueTokenRequest : NEBLObject

/* Address issuing the token 
 */
@property(nonatomic) NSString* issueAddress;
/* Number of tokens to issue 
 */
@property(nonatomic) NSNumber* amount;
/* Number of decimal places the token should be divisble by (0-7) 
 */
@property(nonatomic) NSNumber* divisibility;
/* Fee in satoshi to include in the issuance transaction min 1000000000 (10 NEBL) 
 */
@property(nonatomic) NSNumber* fee;
/* whether the token should be reissuable 
 */
@property(nonatomic) NSNumber* reissuable;

@property(nonatomic) NEBLIssueTokenRequestFlags* flags;

@property(nonatomic) NSArray<NEBLIssueTokenRequestTransfer>* transfer;

@property(nonatomic) NEBLIssueTokenRequestMetadata* metadata;

@end
