#import <Foundation/Foundation.h>
#import "NEBLObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "NEBLGetTokenMetadataResponseMetadataOfIssuenceDataUserDataMeta.h"
@protocol NEBLGetTokenMetadataResponseMetadataOfIssuenceDataUserDataMeta;
@class NEBLGetTokenMetadataResponseMetadataOfIssuenceDataUserDataMeta;



@protocol NEBLGetTokenMetadataResponseMetadataOfUtxoUserData
@end

@interface NEBLGetTokenMetadataResponseMetadataOfUtxoUserData : NEBLObject


@property(nonatomic) NSArray<NEBLGetTokenMetadataResponseMetadataOfIssuenceDataUserDataMeta>* meta;

@end
