#import <Foundation/Foundation.h>
#import "NEBLObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol NEBLGetSyncResponse
@end

@interface NEBLGetSyncResponse : NEBLObject

/* Current sync status [optional]
 */
@property(nonatomic) NSString* status;
/* Current blockchain height [optional]
 */
@property(nonatomic) NSNumber* blockChainHeight;
/* Current sync percentage [optional]
 */
@property(nonatomic) NSNumber* syncPercentage;
/* Height node is synced to [optional]
 */
@property(nonatomic) NSNumber* height;
/* Recent sync error messages [optional]
 */
@property(nonatomic) NSString* error;
/* Node type [optional]
 */
@property(nonatomic) NSString* type;

@end
