#import <Foundation/Foundation.h>
#import "NEBLObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol NEBLGetTransactionInfoResponseTokens
@end

@interface NEBLGetTransactionInfoResponseTokens : NEBLObject

/* ID of the token [optional]
 */
@property(nonatomic) NSString* tokenId;
/* Number of tokens [optional]
 */
@property(nonatomic) NSNumber* amount;
/* TXID the token was issued in [optional]
 */
@property(nonatomic) NSString* issueTxid;
/* Decimal places the token is divisible to [optional]
 */
@property(nonatomic) NSNumber* divisibility;
/* Whether issuance of more tokens is locked [optional]
 */
@property(nonatomic) NSNumber* lockStatus;
/* Whether the tokens are aggregatable [optional]
 */
@property(nonatomic) NSString* aggregationPolicy;

@end
