#import <Foundation/Foundation.h>
#import "NEBLObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "NEBLGetTokenMetadataResponseMetadataOfIssuance.h"
#import "NEBLGetTokenMetadataResponseMetadataOfUtxo.h"
@protocol NEBLGetTokenMetadataResponseMetadataOfIssuance;
@class NEBLGetTokenMetadataResponseMetadataOfIssuance;
@protocol NEBLGetTokenMetadataResponseMetadataOfUtxo;
@class NEBLGetTokenMetadataResponseMetadataOfUtxo;



@protocol NEBLGetTokenMetadataResponse
@end

@interface NEBLGetTokenMetadataResponse : NEBLObject

/* ID of the token [optional]
 */
@property(nonatomic) NSString* tokenId;
/* Example UTXO containing this token. [optional]
 */
@property(nonatomic) NSString* someUtxo;
/* Decimal places the token is divisible to [optional]
 */
@property(nonatomic) NSNumber* divisibility;
/* Whether issuance of more tokens is locked [optional]
 */
@property(nonatomic) NSNumber* lockStatus;
/* Whether the tokens are aggregatable [optional]
 */
@property(nonatomic) NSString* aggregationPolicy;
/* Total tokens issued in initial issuance [optional]
 */
@property(nonatomic) NSNumber* initialIssuanceAmount;
/* Total number of tokens in supply [optional]
 */
@property(nonatomic) NSNumber* totalSupply;
/* Total number of addresses this token is held at [optional]
 */
@property(nonatomic) NSNumber* numOfHolders;
/* Total number of transactions of this token [optional]
 */
@property(nonatomic) NSNumber* numOfTransfers;
/* Total number of times this token has been issued [optional]
 */
@property(nonatomic) NSNumber* numOfIssuance;
/* Number of times tokens have been burned [optional]
 */
@property(nonatomic) NSNumber* numOfBurns;
/* Block number token was issued in [optional]
 */
@property(nonatomic) NSNumber* firstBlock;
/* TXID the token was issued with [optional]
 */
@property(nonatomic) NSString* issuanceTxid;
/* Address that issued the tokens [optional]
 */
@property(nonatomic) NSString* issueAddress;

@property(nonatomic) NEBLGetTokenMetadataResponseMetadataOfIssuance* metadataOfIssuance;

@property(nonatomic) NEBLGetTokenMetadataResponseMetadataOfUtxo* metadataOfUtxo;

@end
