#import <Foundation/Foundation.h>
#import "NEBLObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol NEBLGetFaucetResponseData
@end

@interface NEBLGetFaucetResponseData : NEBLObject

/* TXID of a successful withdrawal [optional]
 */
@property(nonatomic) NSString* txId;

@end
