#import <Foundation/Foundation.h>
#import "NEBLObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol NEBLIssueTokenRequestMetadataRulesHolders
@end

@interface NEBLIssueTokenRequestMetadataRulesHolders : NEBLObject

/* Address that can hold the token [optional]
 */
@property(nonatomic) NSString* address;
/* Whether this rule can be modified in future transactions [optional]
 */
@property(nonatomic) NSNumber* locked;

@end
