#import <Foundation/Foundation.h>
#import "NEBLObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "NEBLGetTokenHoldersResponseHolders.h"
@protocol NEBLGetTokenHoldersResponseHolders;
@class NEBLGetTokenHoldersResponseHolders;



@protocol NEBLGetTokenHoldersResponse
@end

@interface NEBLGetTokenHoldersResponse : NEBLObject

/* TokenId of the token [optional]
 */
@property(nonatomic) NSString* tokenId;

@property(nonatomic) NSArray<NEBLGetTokenHoldersResponseHolders>* holders;
/* How many decimal points the token is divisble to [optional]
 */
@property(nonatomic) NSNumber* divibility;
/* Whether new issuances of this token are locked [optional]
 */
@property(nonatomic) NSNumber* lockStatus;
/* Whether the tokesn are aggregatable [optional]
 */
@property(nonatomic) NSString* aggregationPolicy;
/* A UTXO of this token [optional]
 */
@property(nonatomic) NSString* someUtxo;

@end
