#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIBurnTokenRequestBurn
@end

@interface OAIBurnTokenRequestBurn : OAIObject

/* Amount of tokens to burn [optional]
 */
@property(nonatomic) NSNumber* amount;
/* Unique token id we are burning [optional]
 */
@property(nonatomic) NSString* tokenId;

@end
