#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIGetTokenMetadataResponseMetadataOfIssuanceDataUserDataMeta
@end

@interface OAIGetTokenMetadataResponseMetadataOfIssuanceDataUserDataMeta : OAIObject


@property(nonatomic) NSString* key;

@property(nonatomic) NSString* value;

@end
