#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIGetTxResponse.h"
@protocol OAIGetTxResponse;
@class OAIGetTxResponse;



@protocol OAIGetTxsResponse
@end

@interface OAIGetTxsResponse : OAIObject

/* Number of pages of transactions [optional]
 */
@property(nonatomic) NSNumber* pagesTotal;
/* Array of transaction objects [optional]
 */
@property(nonatomic) NSArray<OAIGetTxResponse>* txs;

@end
