#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIGetAddressInfoResponseUtxos.h"
@protocol OAIGetAddressInfoResponseUtxos;
@class OAIGetAddressInfoResponseUtxos;



@protocol OAIGetAddressInfoResponse
@end

@interface OAIGetAddressInfoResponse : OAIObject

/* The Neblio Address [optional]
 */
@property(nonatomic) NSString* address;
/* Array of UTXOs held at this address. [optional]
 */
@property(nonatomic) NSArray<OAIGetAddressInfoResponseUtxos>* utxos;

@end
