#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIGetFaucetResponseData.h"
@protocol OAIGetFaucetResponseData;
@class OAIGetFaucetResponseData;



@protocol OAIGetFaucetResponse
@end

@interface OAIGetFaucetResponse : OAIObject

/* Whether the withdrawal was successful [optional]
 */
@property(nonatomic) NSString* status;

@property(nonatomic) OAIGetFaucetResponseData* data;

@end
