#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIGetTransactionInfoResponseScriptSig.h"
@protocol OAIGetTransactionInfoResponseScriptSig;
@class OAIGetTransactionInfoResponseScriptSig;



@protocol OAIGetTxResponseVin
@end

@interface OAIGetTxResponseVin : OAIObject

/* TXID of the input [optional]
 */
@property(nonatomic) NSString* txid;
/* output index [optional]
 */
@property(nonatomic) NSNumber* vout;

@property(nonatomic) OAIGetTransactionInfoResponseScriptSig* scriptSig;

@property(nonatomic) NSNumber* sequence;
/* Value of input in NEBL [optional]
 */
@property(nonatomic) NSNumber* value;
/* Value of input in NEBL satoshi [optional]
 */
@property(nonatomic) NSNumber* valueSat;
/* input index [optional]
 */
@property(nonatomic) NSNumber* n;

@end
