#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIIssueTokenRequestMetadataRulesExpiration.h"
#import "OAIIssueTokenRequestMetadataRulesFees.h"
#import "OAIIssueTokenRequestMetadataRulesHolders.h"
@protocol OAIIssueTokenRequestMetadataRulesExpiration;
@class OAIIssueTokenRequestMetadataRulesExpiration;
@protocol OAIIssueTokenRequestMetadataRulesFees;
@class OAIIssueTokenRequestMetadataRulesFees;
@protocol OAIIssueTokenRequestMetadataRulesHolders;
@class OAIIssueTokenRequestMetadataRulesHolders;



@protocol OAIIssueTokenRequestMetadataRules
@end

@interface OAIIssueTokenRequestMetadataRules : OAIObject


@property(nonatomic) OAIIssueTokenRequestMetadataRulesFees* fees;
/* Array of objects describing what addresses can hold the token [optional]
 */
@property(nonatomic) NSArray<OAIIssueTokenRequestMetadataRulesHolders>* holders;

@property(nonatomic) OAIIssueTokenRequestMetadataRulesExpiration* expiration;

@end
