#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIGetTokenMetadataResponseMetadataOfIssuanceDataUserData.h"
#import "OAIIssueTokenRequestMetadataEncryptions.h"
#import "OAIIssueTokenRequestMetadataRules.h"
#import "OAIIssueTokenRequestMetadataUrls.h"
@protocol OAIGetTokenMetadataResponseMetadataOfIssuanceDataUserData;
@class OAIGetTokenMetadataResponseMetadataOfIssuanceDataUserData;
@protocol OAIIssueTokenRequestMetadataEncryptions;
@class OAIIssueTokenRequestMetadataEncryptions;
@protocol OAIIssueTokenRequestMetadataRules;
@class OAIIssueTokenRequestMetadataRules;
@protocol OAIIssueTokenRequestMetadataUrls;
@class OAIIssueTokenRequestMetadataUrls;



@protocol OAIIssueTokenRequestMetadata
@end

@interface OAIIssueTokenRequestMetadata : OAIObject

/* Token Symbol it will be identified by (ex. NIBBL) [optional]
 */
@property(nonatomic) NSString* tokenName;
/* Name of token issuer [optional]
 */
@property(nonatomic) NSString* issuer;
/* Long name or description of token (ex. Nibble) [optional]
 */
@property(nonatomic) NSString* _description;

@property(nonatomic) NSArray<OAIIssueTokenRequestMetadataUrls>* urls;

@property(nonatomic) OAIGetTokenMetadataResponseMetadataOfIssuanceDataUserData* userData;
/* Array of encryption instruction objects for encrypting userData [optional]
 */
@property(nonatomic) NSArray<OAIIssueTokenRequestMetadataEncryptions>* encryptions;

@property(nonatomic) OAIIssueTokenRequestMetadataRules* rules;

@end
