#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIIssueTokenRequestMetadataRulesFeesItems.h"
@protocol OAIIssueTokenRequestMetadataRulesFeesItems;
@class OAIIssueTokenRequestMetadataRulesFeesItems;



@protocol OAIIssueTokenRequestMetadataRulesFees
@end

@interface OAIIssueTokenRequestMetadataRulesFees : OAIObject

/* Array of objects describing fee rules [optional]
 */
@property(nonatomic) NSArray<OAIIssueTokenRequestMetadataRulesFeesItems>* items;
/* Whether this rule can be modified in future transactions [optional]
 */
@property(nonatomic) NSNumber* locked;

@end
