#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIIssueTokenRequestFlags.h"
#import "OAIIssueTokenRequestMetadata.h"
#import "OAIIssueTokenRequestTransfer.h"
@protocol OAIIssueTokenRequestFlags;
@class OAIIssueTokenRequestFlags;
@protocol OAIIssueTokenRequestMetadata;
@class OAIIssueTokenRequestMetadata;
@protocol OAIIssueTokenRequestTransfer;
@class OAIIssueTokenRequestTransfer;



@protocol OAIIssueTokenRequest
@end

@interface OAIIssueTokenRequest : OAIObject

/* Address issuing the token 
 */
@property(nonatomic) NSString* issueAddress;
/* Number of tokens to issue 
 */
@property(nonatomic) NSNumber* amount;
/* Number of decimal places the token should be divisble by (0-7) 
 */
@property(nonatomic) NSNumber* divisibility;
/* Fee in satoshi to include in the issuance transaction min 1000000000 (10 NEBL) 
 */
@property(nonatomic) NSNumber* fee;
/* whether the token should be reissuable 
 */
@property(nonatomic) NSNumber* reissuable;

@property(nonatomic) OAIIssueTokenRequestFlags* flags;

@property(nonatomic) NSArray<OAIIssueTokenRequestTransfer>* transfer;

@property(nonatomic) OAIIssueTokenRequestMetadata* metadata;

@end
