#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Neblio REST API Suite
* APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAISendTokenRequestTo
@end

@interface OAISendTokenRequestTo : OAIObject

/* Address to transfer tokens to [optional]
 */
@property(nonatomic) NSString* address;
/* Number of tokens to send [optional]
 */
@property(nonatomic) NSNumber* amount;
/* ID of token we are sending [optional]
 */
@property(nonatomic) NSString* tokenId;

@end
